services:
  postgresqldb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=web_chat
    volumes:
    - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLIENT_URL=http://localhost:5173

      - DB_NAME=web_chat
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=postgresqldb
    depends_on:
      - postgresqldb
  
volumes:
  db: